In [1]:
import pandas as pd

In [12]:
unsorted_imdb_rating = pd.read_csv('unsorted_imdb_rating.csv')

In [15]:
unsorted_imdb_rating

,star_rating,title,genre,duration
0,9.3,The Shawshank Redemption,Crime,142
1,9.1,The Godfather,Crime,175
2,9.2,The Godfather: Part II,Crime,200
3,9.0,The Dark Knight,Action,152
4,8.9,Pulp Fiction,Crime,154
5,8.8,12 Angry Men,Drama,96
6,8.7,"The Good, the Bad and the Ugly",Western,161
7,8.9,The Lord of the Rings: The Return of the King,Adventure,201
8,8.3,Schindler's List,Biography,195
9,8.1,Fight Club,Drama,139

In [16]:
unsorted_imdb_rating.index = [8,9,1,3,2,4,5,7,6,0]

In [17]:
unsorted_imdb_rating

,star_rating,title,genre,duration
8,9.3,The Shawshank Redemption,Crime,142
9,9.1,The Godfather,Crime,175
1,9.2,The Godfather: Part II,Crime,200
3,9.0,The Dark Knight,Action,152
2,8.9,Pulp Fiction,Crime,154
4,8.8,12 Angry Men,Drama,96
5,8.7,"The Good, the Bad and the Ugly",Western,161
7,8.9,The Lord of the Rings: The Return of the King,Adventure,201
6,8.3,Schindler's List,Biography,195
0,8.1,Fight Club,Drama,139

In [18]:
unsorted_imdb_rating.sort_index()

,star_rating,title,genre,duration
0,8.1,Fight Club,Drama,139
1,9.2,The Godfather: Part II,Crime,200
2,8.9,Pulp Fiction,Crime,154
3,9.0,The Dark Knight,Action,152
4,8.8,12 Angry Men,Drama,96
5,8.7,"The Good, the Bad and the Ugly",Western,161
6,8.3,Schindler's List,Biography,195
7,8.9,The Lord of the Rings: The Return of the King,Adventure,201
8,9.3,The Shawshank Redemption,Crime,142
9,9.1,The Godfather,Crime,175

In [19]:
unsorted_imdb_rating.sort_index(ascending=False)

,star_rating,title,genre,duration
9,9.1,The Godfather,Crime,175
8,9.3,The Shawshank Redemption,Crime,142
7,8.9,The Lord of the Rings: The Return of the King,Adventure,201
6,8.3,Schindler's List,Biography,195
5,8.7,"The Good, the Bad and the Ugly",Western,161
4,8.8,12 Angry Men,Drama,96
3,9.0,The Dark Knight,Action,152
2,8.9,Pulp Fiction,Crime,154
1,9.2,The Godfather: Part II,Crime,200
0,8.1,Fight Club,Drama,139

In [20]:
unsorted_imdb_rating.sort_index(axis=1)

,duration,genre,star_rating,title
8,142,Crime,9.3,The Shawshank Redemption
9,175,Crime,9.1,The Godfather
1,200,Crime,9.2,The Godfather: Part II
3,152,Action,9.0,The Dark Knight
2,154,Crime,8.9,Pulp Fiction
4,96,Drama,8.8,12 Angry Men
5,161,Western,8.7,"The Good, the Bad and the Ugly"
7,201,Adventure,8.9,The Lord of the Rings: The Return of the King
6,195,Biography,8.3,Schindler's List
0,139,Drama,8.1,Fight Club

In [22]:
unsorted_imdb_rating['star_rating'].sort_index()

0    8.1
1    9.2
2    8.9
3    9.0
4    8.8
5    8.7
6    8.3
7    8.9
8    9.3
9    9.1
Name: star_rating, dtype: float64

In [23]:
unsorted_imdb_rating['genre'].sort_index()

0        Drama
1        Crime
2        Crime
3       Action
4        Drama
5      Western
6    Biography
7    Adventure
8        Crime
9        Crime
Name: genre, dtype: object

In [24]:
unsorted_imdb_rating.sort_values(by='duration')

,star_rating,title,genre,duration
4,8.8,12 Angry Men,Drama,96
0,8.1,Fight Club,Drama,139
8,9.3,The Shawshank Redemption,Crime,142
3,9.0,The Dark Knight,Action,152
2,8.9,Pulp Fiction,Crime,154
5,8.7,"The Good, the Bad and the Ugly",Western,161
9,9.1,The Godfather,Crime,175
6,8.3,Schindler's List,Biography,195
1,9.2,The Godfather: Part II,Crime,200
7,8.9,The Lord of the Rings: The Return of the King,Adventure,201

In [25]:
unsorted_imdb_rating.sort_values(by='genre')

,star_rating,title,genre,duration
3,9.0,The Dark Knight,Action,152
7,8.9,The Lord of the Rings: The Return of the King,Adventure,201
6,8.3,Schindler's List,Biography,195
8,9.3,The Shawshank Redemption,Crime,142
9,9.1,The Godfather,Crime,175
1,9.2,The Godfather: Part II,Crime,200
2,8.9,Pulp Fiction,Crime,154
4,8.8,12 Angry Men,Drama,96
0,8.1,Fight Club,Drama,139
5,8.7,"The Good, the Bad and the Ugly",Western,161

In [27]:
unsorted_imdb_rating[['star_rating','title','genre']].sort_values(by=['genre','star_rating'])

   star_rating                                          title      genre
3          9.0                                The Dark Knight     Action
7          8.9  The Lord of the Rings: The Return of the King  Adventure
6          8.3                               Schindler's List  Biography
2          8.9                                   Pulp Fiction      Crime
9          9.1                                  The Godfather      Crime
1          9.2                         The Godfather: Part II      Crime
8          9.3                       The Shawshank Redemption      Crime
0          8.1                                     Fight Club      Drama
4          8.8                                   12 Angry Men      Drama
5          8.7                 The Good, the Bad and the Ugly    Western